apiVersion: v1
kind: Service
metadata:
  name: fs-{{ .Values.tenant.identifier }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: fs-{{ .Values.tenant.identifier }}
spec:
  type: ClusterIP
  selector:
    app: fs-{{ .Values.tenant.identifier }}
    tier: backend
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
